import type { RetrievalContext } from "../../src/lib/retrieval/types";
import type { NarratedDraft, PlannerDraft } from "../../src/lib/generation/types";

export const retrievalContext: RetrievalContext = {
  request: {
    originAddress: "St. Louis, MO",
    destinationArea: "Orlando, FL",
    startDate: "2026-07-06",
    endDate: "2026-07-08",
    partyAdults: 2,
    partyChildren: 2,
    childrenAges: [6, 9],
    interests: ["theme parks", "seafood"],
    budgetLevel: "moderate",
    dietaryNeeds: ["peanut allergy"],
    mobilityCategory: "stroller",
    travelStyle: "balanced",
  },
  candidateGroups: {
    restaurant: [
      {
        id: "place-restaurant-1",
        source: "google_places",
        name: "Garden Grill",
        address: "Orlando, FL",
        location: { lat: 28.37, lng: -81.55 },
        category: "restaurant",
        businessStatus: "OPERATIONAL",
        rating: 4.4,
        ratingCount: 128,
        priceLevel: 2,
        types: ["restaurant"],
        fetchedAt: "2026-06-11T12:00:00.000Z",
        cacheStatus: "fresh",
      },
    ],
    attraction: [
      {
        id: "place-attraction-1",
        source: "google_places",
        name: "Lake Eola Park",
        address: "Orlando, FL",
        location: { lat: 28.54, lng: -81.37 },
        category: "attraction",
        businessStatus: "OPERATIONAL",
        rating: 4.6,
        ratingCount: 2000,
        priceLevel: null,
        types: ["park", "tourist_attraction"],
        fetchedAt: "2026-06-11T12:00:00.000Z",
        cacheStatus: "fresh",
      },
    ],
    hotel: [],
    fuel: [],
    rest: [],
    park: [],
    other: [],
  },
  route: {
    source: "google_routes",
    origin: "St. Louis, MO",
    destination: "Orlando, FL",
    distanceMeters: 1609344,
    durationSeconds: 54000,
    polyline: "encoded",
    segments: [],
    fetchedAt: "2026-06-11T12:00:00.000Z",
    cacheStatus: "fresh",
  },
  warnings: [],
  errors: [],
  generatedAt: "2026-06-11T12:00:00.000Z",
};

export const validPlannerDraft: PlannerDraft = {
  title: "Orlando Family Road Trip",
  summary: "A balanced two-day Orlando plan.",
  days: [
    {
      dayNumber: 1,
      date: "2026-07-06",
      label: "Arrival and Easy Orlando Evening",
      fromLocation: "St. Louis, MO",
      toLocation: "Orlando, FL",
      totalMiles: 1000,
      driveTimeMinutes: 900,
      stops: [
        {
          stableStopKey: "day-1-drive",
          orderIndex: 0,
          name: "Drive to Orlando",
          type: "drive",
          sourcePlaceId: null,
          address: null,
          lat: null,
          lng: null,
          eta: null,
          priceLevel: null,
          googleRating: null,
          hoursSummary: null,
        },
        {
          stableStopKey: "day-1-dinner",
          orderIndex: 1,
          name: "Garden Grill",
          type: "restaurant",
          sourcePlaceId: "place-restaurant-1",
          address: "Orlando, FL",
          lat: 28.37,
          lng: -81.55,
          eta: null,
          priceLevel: 2,
          googleRating: 4.4,
          hoursSummary: null,
        },
      ],
    },
    {
      dayNumber: 2,
      date: "2026-07-07",
      label: "Low-Key Orlando Day",
      fromLocation: "Orlando, FL",
      toLocation: "Orlando, FL",
      totalMiles: 15,
      driveTimeMinutes: 45,
      stops: [
        {
          stableStopKey: "day-2-park",
          orderIndex: 0,
          name: "Lake Eola Park",
          type: "attraction",
          sourcePlaceId: "place-attraction-1",
          address: "Orlando, FL",
          lat: 28.54,
          lng: -81.37,
          eta: null,
          priceLevel: null,
          googleRating: 4.6,
          hoursSummary: null,
        },
      ],
    },
  ],
};

export const narratedDraft: NarratedDraft = {
  ...validPlannerDraft,
  summary: "Consider this balanced Orlando plan with an easy arrival and a low-key park day.",
  days: validPlannerDraft.days.map((day) => ({
    ...day,
    aiSummary: "You might enjoy keeping this day flexible for the kids.",
    stops: day.stops.map((stop) => ({
      ...stop,
      description: `A popular choice is ${stop.name}.`,
      tips: "Consider checking the map before you leave.",
    })),
  })),
};
